# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nrpc.proto',
  package='sogou.nlu.rpc',
  syntax='proto2',
  serialized_pb=_b('\n\nnrpc.proto\x12\rsogou.nlu.rpc\"\x86\x01\n\x08NrpcMeta\x12/\n\x07request\x18\x01 \x01(\x0b\x32\x1e.sogou.nlu.rpc.NrpcRequestMeta\x12\x31\n\x08response\x18\x02 \x01(\x0b\x32\x1f.sogou.nlu.rpc.NrpcResponseMeta\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\x03\"\x9d\x01\n\x0fNrpcRequestMeta\x12\x14\n\x0cservice_name\x18\x01 \x02(\t\x12\x13\n\x0bmethod_name\x18\x02 \x02(\t\x12\x14\n\x0crequest_body\x18\x03 \x01(\x0c\x12\x0e\n\x06log_id\x18\x04 \x01(\x03\x12\x10\n\x08trace_id\x18\x05 \x01(\x03\x12\x0f\n\x07span_id\x18\x06 \x01(\x03\x12\x16\n\x0eparent_span_id\x18\x07 \x01(\x03\"Q\n\x10NrpcResponseMeta\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x12\n\nerror_text\x18\x02 \x01(\t\x12\x15\n\rresponse_body\x18\x03 \x01(\x0c\x42\'\n\rsogou.nlu.rpcB\rsogou.nlu.rpc\x80\x01\x01\x88\x01\x01\x90\x01\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NRPCMETA = _descriptor.Descriptor(
  name='NrpcMeta',
  full_name='sogou.nlu.rpc.NrpcMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='sogou.nlu.rpc.NrpcMeta.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='sogou.nlu.rpc.NrpcMeta.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='sogou.nlu.rpc.NrpcMeta.correlation_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=164,
)


_NRPCREQUESTMETA = _descriptor.Descriptor(
  name='NrpcRequestMeta',
  full_name='sogou.nlu.rpc.NrpcRequestMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='sogou.nlu.rpc.NrpcRequestMeta.service_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='sogou.nlu.rpc.NrpcRequestMeta.method_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_body', full_name='sogou.nlu.rpc.NrpcRequestMeta.request_body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_id', full_name='sogou.nlu.rpc.NrpcRequestMeta.log_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trace_id', full_name='sogou.nlu.rpc.NrpcRequestMeta.trace_id', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='span_id', full_name='sogou.nlu.rpc.NrpcRequestMeta.span_id', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent_span_id', full_name='sogou.nlu.rpc.NrpcRequestMeta.parent_span_id', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=324,
)


_NRPCRESPONSEMETA = _descriptor.Descriptor(
  name='NrpcResponseMeta',
  full_name='sogou.nlu.rpc.NrpcResponseMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='sogou.nlu.rpc.NrpcResponseMeta.error_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_text', full_name='sogou.nlu.rpc.NrpcResponseMeta.error_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response_body', full_name='sogou.nlu.rpc.NrpcResponseMeta.response_body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=407,
)

_NRPCMETA.fields_by_name['request'].message_type = _NRPCREQUESTMETA
_NRPCMETA.fields_by_name['response'].message_type = _NRPCRESPONSEMETA
DESCRIPTOR.message_types_by_name['NrpcMeta'] = _NRPCMETA
DESCRIPTOR.message_types_by_name['NrpcRequestMeta'] = _NRPCREQUESTMETA
DESCRIPTOR.message_types_by_name['NrpcResponseMeta'] = _NRPCRESPONSEMETA

NrpcMeta = _reflection.GeneratedProtocolMessageType('NrpcMeta', (_message.Message,), dict(
  DESCRIPTOR = _NRPCMETA,
  __module__ = 'nrpc_pb2'
  # @@protoc_insertion_point(class_scope:sogou.nlu.rpc.NrpcMeta)
  ))
_sym_db.RegisterMessage(NrpcMeta)

NrpcRequestMeta = _reflection.GeneratedProtocolMessageType('NrpcRequestMeta', (_message.Message,), dict(
  DESCRIPTOR = _NRPCREQUESTMETA,
  __module__ = 'nrpc_pb2'
  # @@protoc_insertion_point(class_scope:sogou.nlu.rpc.NrpcRequestMeta)
  ))
_sym_db.RegisterMessage(NrpcRequestMeta)

NrpcResponseMeta = _reflection.GeneratedProtocolMessageType('NrpcResponseMeta', (_message.Message,), dict(
  DESCRIPTOR = _NRPCRESPONSEMETA,
  __module__ = 'nrpc_pb2'
  # @@protoc_insertion_point(class_scope:sogou.nlu.rpc.NrpcResponseMeta)
  ))
_sym_db.RegisterMessage(NrpcResponseMeta)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\rsogou.nlu.rpcB\rsogou.nlu.rpc\200\001\001\210\001\001\220\001\001'))
# @@protoc_insertion_point(module_scope)
